project:
  type: website
  output-dir: docs

website:
  title: "Marlaina Lascano"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - project page.qmd
      - free for all.qmd
      - resume.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

